//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellCity.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public int userId { get; set; }
        public int productId { get; set; }
        public int wishListID { get; set; }
        public int numberOfItem { get; set; }
        public Nullable<decimal> totalPrice { get; set; }
        public Nullable<System.DateTime> dateOfOrder { get; set; }
        public string OrderStatus { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        public virtual WishList WishList { get; set; }
    }
}
